### ISSUE TITLE
Extent Scope of COVID Credential Vocab beyond Vaccination Proofs

### ISSUE THREAD

**Issue by cstoecker** [w3c-ccg/vaccination-vocab#11]
Currently, work is being done on an interoperable solution and portable vocab for **COVID vaccination proofs** that can be implemented across industry sectors and country borders. It is expected that vaccination proofs might be required for **getting access** to facilities, services or public transport to reduce the risk of COVID infections and super spreader events.

However, is unclear if COVID vaccinated people can further spread the disease or not. For ethical, social and economic reasons, non-vaccinated persons should be offered services to prove that they are not COVID-infected at a given time. Because of these reasons **COVID Test Passes** (e.g. Lab PCR tests or Antigen Quick Tests) and **Immunization Passes** shall be added to the mix of required COVID credentials that might be required in a given jurisdiction to get access facilities, services or public transport.

This extension of COVID-related credentials is to **avoid the aforementioned positive discrimination** against vaccinated persons and to increase safety of facilities, services and events. 

Policies and compliance requirements might depend on local regulations. For instance, some countries are discussing to introduce **Antigen Quick Tests** such as 

1. Health Care Professionals Antigen Tests (HCP Antigen Tests)
2. Antigen Quick Tests under Supervision

**HCP Antigen Tests** are supervised by Health Care Professionals.  Whereas **Antigen Quick Tests under Supervision** can be done in a retail store or at work and are supervised by qualified / trained personnel. These test passes might qualify for a give time frame to access facilities, services and events, aka **Test Pass for 24 Hours**. 

**Credentialing solutions** for vaccinated and non-vaccinated persons require the introduction of a secure, verifiable test passport that is largely secured against forgery. When introducing such a solution, a balance must be struck between the objectives of speed, scalability, security and privacy. There are multiple implementation patterns to do this. 

We suggest to take the above considerations into account and extent the scope of this COVID vaccination proofs to **COVID credentials** in general and to include further credentials such as PCR, antibody and antigen quick test credentials.

**Comment by tplooker** [comment]
@cstoecker as spoken about on a call after this issue was created we resolved to create a seperate vocab for testing, so I'm going to close this issue, please re-open if you need to
