### ISSUE TITLE
COVID Credential Proposal - COVID 24h Test Pass 

### ISSUE THREAD

**Issue by cstoecker** [w3c-ccg/vaccination-vocab#12]
We propose to add a **COVID Test Pass Credential** to the repo. 

The following example shall outline how a test pass credential can be structured. The structure is pretty similar to the **vaccination proof** schema. 

It shall be understood that many test pass attributes are **optional** (i.e. not required in the respective schema). For instance, an **Antigen Quick Test under Supervision** might be done in a retail store and was therefore not done by a HCP. Also the level of personalization might vary by country and use case type (air plan flight vs. local restaurant visit).

Example:

`{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/covidcredentials/v1"
  ],
  "type": [
    "VerifiableCredential",
    "AntigenTestCertificate"
  ],
  "id": "urn:drk:af5vshde843jf831j128fj",
  "name": "COVID-19 Antigen Test Certificate",
  "description": "COVID-19 Antigen Test Certificate",
  "issuanceDate": "2021-02-19T12:19:52Z",
  "expirationDate": "2021-02-20T12:19:52Z",
  "issuer": "did:web:www.drk.de:center123:did.json",
  "credentialSubject": {
    "type": "AntigenTestEvent",
    "testCentre": "DRK123, Düsseldorf",
    "healthProfessional": "n/a",
    "countryOfTesting": "DE",
    "testedPerson": {
      "type": "TestedPerson",
      "givenName": "HANS",
      "familyName": "MUSTERMANN",
      "gender": "Male",
      "birthDate": "1973-05-18"
    },
    "testResult": "negativ",
    "antigenTest": {
      "type": "Antigen Test",
      "disease": "COVID-19",
      "productCode": "09417125702",
      "medicinalProductName": "SARS-CoV-2 Rapid Antigen Nasal",
      "marketingAuthorizationHolder": "Roche"
    }
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-02-18T23:00:15Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..vD_vXJCWdeGpN-qKHDIlzgGC0auRPcwp3O1sOI-gN8z3UD4pI0HO_77ob5KHhhU1ugLrrwrMsKv71mqHBn-dBg",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:web:www.drk.de:center123:did.json#z6MkiY62766b1LJkExWMsM3QG4WtX7QpY823dxoYzr9qZvJ3"
  }
}`

**Comment by cstoecker** [comment]
@tplooker : Is the test pass something you might to include into a COVID credentialing vocab?

**Comment by tplooker** [comment]
@cstoecker as spoken about on a call after this issue was created we resolved to create a seperate vocab for testing, so I'm going to close this issue, please re-open if you need to
